# Generated by Django 5.1.4 on 2026-09-04 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('HALL_TICKET', 'Hall Ticket Generated'), ('EXAM_SCHEDULED', 'Exam Scheduled'), ('RESULT_PUBLISHED', 'Result Published'), ('VIOLATION_FLAGGED', 'Proctoring Violation Flagged'), ('PAPER_APPROVED', 'Question Paper Approved'), ('ELIGIBILITY_UPDATE', 'Eligibility Status Updated'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
