# Generated by Django 5.1.4 on 2026-09-07 14:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0008_add_room_department'),
        ('users', '0004_add_section_to_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CIEConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cie_number', models.CharField(choices=[('CIE_1', 'CIE 1'), ('CIE_2', 'CIE 2'), ('CIE_3', 'CIE 3')], default='CIE_1', max_length=10)),
                ('max_marks', models.PositiveSmallIntegerField(default=50)),
                ('duration_mins', models.PositiveSmallIntegerField(default=60)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='True when HOD has activated the CIE for students to write')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_faculty', models.ForeignKey(blank=True, help_text='Faculty responsible for conducting this CIE', limit_choices_to={'role__in': ['FACULTY', 'HOD']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cie_configs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cie_configs', to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cie_configurations', to='scheduling.examsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cie_configurations', to='scheduling.subject')),
            ],
            options={
                'db_table': 'cie_configuration',
                'ordering': ['cie_number'],
                'unique_together': {('subject', 'exam_session', 'cie_number')},
            },
        ),
        migrations.CreateModel(
            name='CIEQuestionPaperScrutiny',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('paper_title', models.CharField(max_length=300)),
                ('paper_content', models.TextField(help_text='Question paper content in text/markdown (faculty-entered)')),
                ('answer_key', models.TextField(blank=True, help_text='Answer key / rubric (visible only to HOD and faculty)')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending HOD Review'), ('APPROVED', 'Approved by HOD'), ('REJECTED', 'Rejected – Needs Revision')], db_index=True, default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='HOD approval/rejection note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cie_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrutiny', to='cie.cieconfiguration')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cie_papers', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cie_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cie_question_paper_scrutiny',
            },
        ),
        migrations.CreateModel(
            name='AssignmentMarks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, help_text='Assignment marks out of 10', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('max_marks', models.PositiveSmallIntegerField(default=10)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_assignment_marks', to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_marks', to='scheduling.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_marks', to='users.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_marks', to='scheduling.subject')),
            ],
            options={
                'db_table': 'cie_assignment_marks',
                'unique_together': {('student', 'subject', 'exam_session')},
            },
        ),
        migrations.CreateModel(
            name='CIEMarks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_awarded', models.DecimalField(decimal_places=2, help_text='Marks given to this student for this CIE', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_absent', models.BooleanField(default=False)),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cie_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='cie.cieconfiguration')),
                ('entered_by', models.ForeignKey(limit_choices_to={'role__in': ['FACULTY', 'HOD']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_cie_marks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cie_marks', to='users.student')),
            ],
            options={
                'db_table': 'cie_marks',
                'ordering': ['cie_config__cie_number', 'student__usn'],
                'unique_together': {('student', 'cie_config')},
            },
        ),
    ]
