# Generated by Django 5.1.4 on 2026-09-07 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cie', '0001_initial'),
        ('users', '0004_add_section_to_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIEAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('cie_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cie_attempts', to='cie.cieconfiguration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cie_attempts', to='users.student')),
            ],
            options={
                'db_table': 'cie_attempt',
                'unique_together': {('student', 'cie_config')},
            },
        ),
        migrations.CreateModel(
            name='CIEAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(blank=True, help_text='Stored since CIE might use a simple text-based paper', max_length=500)),
                ('answer_text', models.TextField(blank=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='cie.cieattempt')),
            ],
            options={
                'db_table': 'cie_answer',
            },
        ),
    ]
