# Generated by Django 5.1.4 on 2026-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cie', '0002_cieattempt_cieanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cieanswer',
            name='answer_image_base64',
            field=models.TextField(blank=True, help_text='JSON array of Base64 encoded images of the handwritten pages'),
        ),
    ]
