# Generated by Django 5.1.4 on 2026-09-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cie', '0003_cieanswer_answer_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='cieanswer',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from the handwritten image via OCR'),
        ),
    ]
