# Generated by Django 5.1.4 on 2026-09-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cie', '0004_cieanswer_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cieattempt',
            name='submission_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('NOT_ATTENDED', 'Not Attended')], default='IN_PROGRESS', max_length=20),
        ),
    ]
