# Generated by Django 5.1.4 on 2026-10-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cie', '0005_add_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cieattempt',
            name='proctor_strikes',
            field=models.PositiveSmallIntegerField(default=0, help_text='AI-proctor violations recorded during the attempt (0-3)'),
        ),
    ]
