# Generated by Django 5.1.4 on 2026-09-04 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Faculty member assigned as course coordinator', limit_choices_to={'role__in': ['FACULTY', 'HOD']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
