# Generated by Django 5.1.4 on 2026-09-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_subject_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='exam_sessions', to='scheduling.subject'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='scheduling_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for timetable generation', max_length=255, null=True),
        ),
    ]
