# Generated by Django 5.1.4 on 2026-09-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_examsession_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='co_po_mapping',
            field=models.JSONField(default=dict, help_text="Mapping of COs to POs, e.g. {'CO1': {'PO1': 3, 'PO2': 2}}"),
        ),
    ]
