# Generated by Django 5.1.4 on 2026-09-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_subject_co_po_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='departments',
            field=models.JSONField(blank=True, default=list, help_text="Dept codes included, e.g. ['CSE','ECE']"),
        ),
        migrations.AddField(
            model_name='examsession',
            name='semesters',
            field=models.JSONField(blank=True, default=list, help_text='All semesters included in this session, e.g. [3,5,7]'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Primary semester (nullable for multi-semester CoE sessions)', null=True),
        ),
    ]
