# Generated by Django 5.1.4 on 2026-09-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_add_semesters_departments_to_examsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='exams_per_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum exam sessions per day (1 or 2)'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='selected_slots',
            field=models.JSONField(blank=True, default=list, help_text="Selected time slots, e.g. ['SLOT_M1'] or ['SLOT_M1','SLOT_A1']"),
        ),
    ]
