# Generated by Django 5.1.4 on 2026-09-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_add_exams_per_day_and_selected_slots'),
        ('users', '0003_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this room belongs to (null = shared/common)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='users.department'),
        ),
    ]
