# Generated by Django 5.1.4 on 2026-09-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_add_room_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='session_type',
            field=models.CharField(choices=[('CIE', 'CIE - Continuous Internal Evaluation'), ('SEE', 'SEE - Semester End Examination')], default='SEE', max_length=10),
        ),
    ]
