# Generated by Django 5.1.4 on 2026-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_examsession_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='seat_map',
            field=models.JSONField(blank=True, default=dict, help_text="Mapping of USN to specific seat coordinate, e.g. {'1MS24CS001': 'R1C2'}"),
        ),
    ]
