# Generated by Django 5.1.4 on 2026-09-07 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_timetableslot_seat_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorSessionKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(help_text='Time-locked OTP or cryptographic key, e.g. EVAL-3F8B-4A12', max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Becomes True when invigilator starts the session, unlocking student screens')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('duty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_key', to='scheduling.invigilationduty')),
            ],
            options={
                'db_table': 'scheduling_invigilator_session_key',
            },
        ),
    ]
