# Generated by Django 5.1.4 on 2026-09-11 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_invigilatorsessionkey'),
        ('users', '0004_add_section_to_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamIncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('infraction_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_broadcasted_to_coe', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_incidents', to='users.student')),
                ('timetable_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='scheduling.timetableslot')),
            ],
            options={
                'db_table': 'scheduling_exam_incident_report',
            },
        ),
        migrations.CreateModel(
            name='StudentExamAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('desk_id', models.CharField(help_text='e.g. Desk B-01', max_length=20)),
                ('seat_position', models.CharField(help_text='e.g. Row 1, Col 1', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('malpractice', 'Malpractice'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('is_qr_verified', models.BooleanField(default=False)),
                ('is_biometric_matched', models.BooleanField(default=False)),
                ('booklet_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('dummy_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('digitized_pages_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attendances', to='users.student')),
                ('timetable_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='scheduling.timetableslot')),
            ],
            options={
                'db_table': 'scheduling_student_exam_attendance',
                'unique_together': {('timetable_slot', 'student')},
            },
        ),
    ]
