# Generated by Django 5.1.4 on 2026-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_examincidentreport_studentexamattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bench_style',
            field=models.CharField(choices=[('SINGLE_SEATER', 'Single Seater'), ('DOUBLE_SEATER', 'Double Seater')], default='SINGLE_SEATER', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='cols_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of seat columns in the room'),
        ),
        migrations.AddField(
            model_name='room',
            name='rows_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of seat rows in the room'),
        ),
    ]
