# Generated by Django 5.1.4 on 2026-09-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_add_room_grid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='selected_rooms',
            field=models.JSONField(blank=True, default=list, help_text="Selected room names, e.g. ['CRB-1', 'CRB-2']"),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='selected_slots',
            field=models.JSONField(blank=True, default=list, help_text="Selected time slots, e.g. ['09:30 AM - 11:00 AM']"),
        ),
    ]
