# Generated by Django 5.1.4 on 2026-09-14 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_add_selected_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilationduty',
            name='invigilator',
            field=models.ForeignKey(limit_choices_to={'role__in': ['INVIGILATOR', 'FACULTY', 'EVALUATOR']}, on_delete=django.db.models.deletion.PROTECT, related_name='invigilation_duties', to=settings.AUTH_USER_MODEL),
        ),
    ]
