# Generated by Django 5.1.4 on 2026-10-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_alter_invigilationduty_invigilator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together=set(),
        ),
    ]
