# Generated by Django 5.1.4 on 2026-10-07 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_alter_timetableslot_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableRescheduleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(blank=True, default='', max_length=20)),
                ('subject_name', models.CharField(blank=True, default='', max_length=200)),
                ('room_name', models.CharField(blank=True, default='', max_length=100)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, default='', max_length=15)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_logs', to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_logs', to='scheduling.examsession')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_logs', to='scheduling.timetableslot')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_logs', to='scheduling.subject')),
            ],
            options={
                'db_table': 'scheduling_timetable_reschedule_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
