# Generated by Django 5.1.4 on 2026-09-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteligibility',
            name='assignment_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assignment Marks', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studenteligibility',
            name='cie1_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CIE 1 Marks', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studenteligibility',
            name='cie2_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CIE 2 Marks', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studenteligibility',
            name='cie3_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='CIE 3 Marks', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studenteligibility',
            name='cie_marks',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total Continuous Internal Evaluation marks (Calculated)', max_digits=5, null=True),
        ),
    ]
