# Generated by Django 5.1.4 on 2026-09-07 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_invigilatorsessionkey'),
        ('student', '0001_initial'),
        ('users', '0004_add_section_to_student'),
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEEAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='see_attempts', to='scheduling.examsession')),
                ('session_key', models.ForeignKey(blank=True, help_text='The session key used to unlock this attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.invigilatorsessionkey')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='see_attempts', to='users.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='see_attempts', to='scheduling.subject')),
            ],
            options={
                'db_table': 'student_see_attempt',
                'unique_together': {('student', 'subject', 'exam_session')},
            },
        ),
        migrations.CreateModel(
            name='SEEAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='see_answers', to='vault.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='student.seeattempt')),
            ],
            options={
                'db_table': 'student_see_answer',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
