# Generated by Django 5.1.4 on 2026-10-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_result_cie_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeanswer',
            name='answer_image_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded images of the handwritten pages'),
        ),
        migrations.AddField(
            model_name='seeanswer',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted from the handwritten image via OCR'),
        ),
        migrations.AddField(
            model_name='seeattempt',
            name='proctor_strikes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Proctoring violations recorded during the attempt (max 3)'),
        ),
    ]
