# Generated by Django 5.1.4 on 2026-09-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CHIEF_SUPERINTENDENT', 'Chief Superintendent / CoE'), ('HOD', 'Head of Department'), ('PAPER_SETTER', 'Question Paper Setter'), ('INVIGILATOR', 'Invigilator'), ('EVALUATOR', 'Faculty Evaluator'), ('SCRUTINIZER', 'Scrutinizer'), ('STUDENT', 'Student'), ('SCANNING_OFFICER', 'Scanning Center Superintendent'), ('FACULTY', 'Faculty / Course Teacher')], db_index=True, default='STUDENT', max_length=30),
        ),
    ]
