# Generated by Django 5.1.4 on 2026-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='A', help_text='Class section, e.g. A, B, C', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CHIEF_SUPERINTENDENT', 'Chief Superintendent / CoE'), ('HOD', 'Head of Department'), ('PAPER_SETTER', 'Question Paper Setter'), ('INVIGILATOR', 'Invigilator'), ('EVALUATOR', 'Faculty Evaluator'), ('SCRUTINIZER', 'Scrutinizer'), ('STUDENT', 'Student'), ('SCANNING_OFFICER', 'Scanning Center Superintendent'), ('FACULTY', 'Faculty / Course Teacher'), ('ADMISSION', 'Admission Officer')], db_index=True, default='STUDENT', max_length=30),
        ),
    ]
