# Generated by Django 5.1.4 on 2026-09-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_section_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='historical_duties_count',
            field=models.IntegerField(default=0),
        ),
    ]
