# Generated by Django 5.1.4 on 2026-09-04 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0002_initial'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookletPacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_usn', models.CharField(help_text='USN as written on the booklet cover page', max_length=20)),
                ('booklet_file', models.FileField(help_text='Scanned PDF or image of the answer booklet', upload_to='scanning/booklets/%Y/%m/')),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('LINKED', 'Linked to Student'), ('FAILED', 'Failed to Process')], db_index=True, default='UPLOADED', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('scanning_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booklet_packets', to='scanning.scanningsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booklet_packets', to='users.student')),
            ],
            options={
                'db_table': 'scanning_booklet_packet',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
